server:
  port: 9000

logging:
  level:
    org:
      springframework: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false